// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Trackfinder.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730121036_SeedBestiary")]
    partial class SeedBestiary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CombatMonster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ac")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer");

                    b.Property<int>("Init")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("TemplateId");

                    b.ToTable("CombatMonsters");
                });

            modelBuilder.Entity("Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveMonsterId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("MonsterTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Ac")
                        .HasColumnType("integer");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = "mudcrab-001",
                            Ac = 12,
                            BaseName = "Mudcrab",
                            DetailsJson = "{\r\n  \"level\": 1,\r\n  \"traits\": [\"Beast\", \"Aquatic\"],\r\n  \"speed\": {\r\n    \"walking\": 20,\r\n    \"flying\": 0,\r\n    \"swimming\": 20,\r\n    \"burrowing\": 10,\r\n    \"climbing\": 0\r\n  },\r\n  \"savingThrows\": {\r\n    \"fortitude\": 6,\r\n    \"reflex\": 4,\r\n    \"will\": 2\r\n  },\r\n  \"attacks\": [\r\n    { \"name\": \"Pincer\", \"type\": \"melee\", \"bonus\": 6, \"traits\": [\"agile\", \"finesse\"] }\r\n  ],\r\n  \"loot\": [\r\n    { \"item\": \"Mudcrab Chitin\", \"quantity\": 1 }\r\n  ]\r\n}",
                            MaxHp = 7
                        },
                        new
                        {
                            Id = "draugr-001",
                            Ac = 15,
                            BaseName = "Draugr Deathlord",
                            DetailsJson = "{\r\n  \"level\": 5,\r\n  \"traits\": [\"Undead\", \"Mindless\"],\r\n  \"speed\": {\r\n    \"walking\": 25,\r\n    \"flying\": 0,\r\n    \"swimming\": 0,\r\n    \"burrowing\": 0,\r\n    \"climbing\": 0\r\n  },\r\n  \"savingThrows\": {\r\n    \"fortitude\": 12,\r\n    \"reflex\": 8,\r\n    \"will\": 10\r\n  },\r\n  \"attacks\": [\r\n    { \"name\": \"Ebony Greatsword\", \"type\": \"melee\", \"bonus\": 14, \"traits\": [\"reach\", \"sweep\"] }\r\n  ],\r\n  \"loot\": [\r\n    { \"item\": \"Bone Meal\", \"quantity\": 2 },\r\n    { \"item\": \"Ebony Greatsword\", \"quantity\": 1 }\r\n  ]\r\n}",
                            MaxHp = 85
                        },
                        new
                        {
                            Id = "dragon-001",
                            Ac = 19,
                            BaseName = "Ancient Dragon",
                            DetailsJson = "{\r\n  \"level\": 12,\r\n  \"traits\": [\"Dragon\", \"Fire\"],\r\n  \"speed\": {\r\n    \"walking\": 30,\r\n    \"flying\": 100,\r\n    \"swimming\": 0,\r\n    \"burrowing\": 0,\r\n    \"climbing\": 0\r\n  },\r\n  \"savingThrows\": {\r\n    \"fortitude\": 24,\r\n    \"reflex\": 20,\r\n    \"will\": 22\r\n  },\r\n  \"attacks\": [\r\n    { \"name\": \"Bite\", \"type\": \"melee\", \"bonus\": 26, \"traits\": [\"reach\"] },\r\n    { \"name\": \"Fire Breath\", \"type\": \"ranged\", \"bonus\": 20, \"traits\": [\"magical\", \"fire\"] }\r\n  ],\r\n  \"loot\": [\r\n    { \"item\": \"Dragon Scales\", \"quantity\": 5 },\r\n    { \"item\": \"Dragon Bone\", \"quantity\": 3 }\r\n  ]\r\n}",
                            MaxHp = 250
                        });
                });

            modelBuilder.Entity("CombatMonster", b =>
                {
                    b.HasOne("Encounter", "Encounter")
                        .WithMany("Monsters")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonsterTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encounter");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Encounter", b =>
                {
                    b.Navigation("Monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
